name: Python application

on:
  push:
    branches:
      - "*"  # Trigger on push to any branch
  pull_request:
    branches:
      - "*"  # Trigger on pull request to any branch
  pull_request_target:
    branches:
      - "*"  # Trigger on pull request target to any branch (for merged PRs)

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest  # Run on a Windows environment

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
        shell: pwsh  # Use PowerShell shell for Windows
      - name: Delete __pycache__
        run: |
          Get-ChildItem -Path . -Recurse -Directory -Filter "__pycache__" | ForEach-Object { Remove-Item $_.FullName -Recurse -Force }
        shell: pwsh

      - name: Run tests
        run: |
          pytest test/