name: Python application

on:
  push:
    branches:
      - "*"  # Trigger on push to any branch
  pull_request:
    branches:
      - "*"  # Trigger on pull request to any branch
  pull_request_target:
    branches:
      - "*"  # Trigger on pull request target to any branch (for merged PRs)

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # Use 'ubuntu-latest' for Linux, or 'windows-latest' for Windows if desired

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if Test-Path requirements.txt; then pip install -r requirements.txt; fi
        shell: bash  # Specify bash shell to handle if statement syntax
      - name: Run tests
        run: |
          pytest
